# Generated by Django 3.1.5 on 2021-01-10 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 10, 9, 11, 13, 650039, tzinfo=utc)),
        ),
    ]
