# Generated by Django 3.1.5 on 2021-01-10 09:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20210110_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 10, 9, 15, 56, 335214, tzinfo=utc)),
        ),
    ]
